import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const random = () => Math.floor(Math.random() * 2000)

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1 className={styles.title}>
          &#128075; Welcome to <span className={styles["text-gradient"]}>Simon</span>
        </h1>
      </header>

      <main className={styles.main}>
        <div style={{ width: 200, height: 200, backgroundColor: "#f54fd4", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 150, height: 150, backgroundColor: "#4e4ef3", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 100, height: 100, backgroundColor: "#f54fd4", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 120, height: 120, backgroundColor: "#4e4ef3", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 70, height: 70, backgroundColor: "#f54fd4", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 90, height: 90, backgroundColor: "#4e4ef3", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 200, height: 200, backgroundColor: "#f54fd4", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 150, height: 150, backgroundColor: "#4e4ef3", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 100, height: 100, backgroundColor: "#f54fd4", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 120, height: 120, backgroundColor: "#4e4ef3", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 70, height: 70, backgroundColor: "#f54fd4", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 90, height: 90, backgroundColor: "#4e4ef3", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div className={styles["options-grid"]}>
          <div className={styles.card}>
            <div className={styles["img-container"]}>
              <Image width="50" height="50" src="/eth.png" />
            </div>
            <h2>Earn <span className={styles["text-gradient"]}>ETH</span> by playing</h2>
            <p>
              Players with best score can earn some ETH as a trophy!
            </p>
          </div>
          <div className={styles.card}>
            <div className={styles["wrench-container"]}>
              <p style={{fontSize: 50}}>&#128295;</p>
            </div>
            <h2>Earn <span className={styles["text-gradient"]}>ETH</span> by building</h2>
            <p>
              Be the most feared builder and you will be rewarded!
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/toni-bardina-comas-4a435113a/"
          target="_blank"
          rel="noopener noreferrer"
        >
          🚀 Created by&nbsp;<span className={styles.bold}>Toni Bardina</span>
        </a>
      </footer>
    </div>
  )
}

export default Home
