import type { NextPage } from 'next'
import Head from 'next/head'
import Script from 'next/script'
import { useState } from 'react'
import Builder from '../components/Builder'
import Options from '../components/Options'
import styles from '../styles/Home.module.css'

const random = () => Math.floor(Math.random() * 2000)

const Home: NextPage = () => {
  const [showOptions, setShowOptions] = useState(true)
  const [showBuilder, setShowBuilder] = useState(false)
  const [showPlay, setShowPlay] = useState(false)

  const startBuilder = () => {
    setShowOptions(false)
    setShowBuilder(true)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1 className={styles.title}>
          &#128075; Welcome to <span className={styles["text-gradient"]}>Simon</span>
        </h1>
      </header>

      <main className={styles.main}>
        <div style={{ width: 200, height: 200, backgroundColor: "#f54fd4", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 150, height: 150, backgroundColor: "#4e4ef3", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 100, height: 100, backgroundColor: "#f54fd4", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 120, height: 120, backgroundColor: "#4e4ef3", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 70, height: 70, backgroundColor: "#f54fd4", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 90, height: 90, backgroundColor: "#4e4ef3", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 200, height: 200, backgroundColor: "#f54fd4", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 150, height: 150, backgroundColor: "#4e4ef3", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 100, height: 100, backgroundColor: "#f54fd4", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 120, height: 120, backgroundColor: "#4e4ef3", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 70, height: 70, backgroundColor: "#f54fd4", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        <div style={{ width: 90, height: 90, backgroundColor: "#4e4ef3", top: random(), left: random() }} className={styles["random-gradient-circle"]}></div>
        {showOptions && <Options onClickPlayOption={() => null} onClickBuildOption={startBuilder} />}
        {showBuilder && <Builder />}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/toni-bardina-comas-4a435113a/"
          target="_blank"
          rel="noopener noreferrer"
        >
          🚀 Created by&nbsp;<span className={styles.bold}>Toni Bardina</span>
        </a>
      </footer>
      <Script src="https://cdn.jsdelivr.net/npm/ace-builds@1.4.12/src-min-noconflict/ace.js" type="text/javascript"></Script>
    </div>
  )
}

export default Home
